# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\studioTools\maya\python\tool\publish\rig\ui.ui'
#
# Created: Fri Feb 05 19:19:10 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui
from qtshim import Signal
from qtshim import wrapinstance


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_rigPublishWin(object):
    def setupUi(self, rigPublishWin):
        rigPublishWin.setObjectName(_fromUtf8("rigPublishWin"))
        rigPublishWin.resize(530, 743)
        self.centralwidget = QtGui.QWidget(rigPublishWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.scene_label = QtGui.QLabel(self.centralwidget)
        self.scene_label.setObjectName(_fromUtf8("scene_label"))
        self.gridLayout_2.addWidget(self.scene_label, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.asset_label = QtGui.QLabel(self.centralwidget)
        self.asset_label.setObjectName(_fromUtf8("asset_label"))
        self.gridLayout_2.addWidget(self.asset_label, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cmd_listWidget = QtGui.QListWidget(self.centralwidget)
        self.cmd_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.cmd_listWidget.setObjectName(_fromUtf8("cmd_listWidget"))
        self.gridLayout.addWidget(self.cmd_listWidget, 2, 0, 1, 1)
        self.exe_listWidget = QtGui.QListWidget(self.centralwidget)
        self.exe_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.exe_listWidget.setObjectName(_fromUtf8("exe_listWidget"))
        self.gridLayout.addWidget(self.exe_listWidget, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cmd_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cmd_lineEdit.setObjectName(_fromUtf8("cmd_lineEdit"))
        self.horizontalLayout_4.addWidget(self.cmd_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.preset_comboBox = QtGui.QComboBox(self.centralwidget)
        self.preset_comboBox.setObjectName(_fromUtf8("preset_comboBox"))
        self.horizontalLayout_3.addWidget(self.preset_comboBox)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.refresh_pushButton = QtGui.QPushButton(self.centralwidget)
        self.refresh_pushButton.setObjectName(_fromUtf8("refresh_pushButton"))
        self.gridLayout.addWidget(self.refresh_pushButton, 3, 0, 1, 1)
        self.clear_pushButton = QtGui.QPushButton(self.centralwidget)
        self.clear_pushButton.setObjectName(_fromUtf8("clear_pushButton"))
        self.gridLayout.addWidget(self.clear_pushButton, 3, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.add_pushButton = QtGui.QPushButton(self.centralwidget)
        self.add_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.add_pushButton.setObjectName(_fromUtf8("add_pushButton"))
        self.verticalLayout_3.addWidget(self.add_pushButton)
        self.remove_pushButton = QtGui.QPushButton(self.centralwidget)
        self.remove_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.remove_pushButton.setObjectName(_fromUtf8("remove_pushButton"))
        self.verticalLayout_3.addWidget(self.remove_pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.preset_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.preset_lineEdit.setObjectName(_fromUtf8("preset_lineEdit"))
        self.horizontalLayout_6.addWidget(self.preset_lineEdit)
        self.savePreset_pushButton = QtGui.QPushButton(self.centralwidget)
        self.savePreset_pushButton.setObjectName(_fromUtf8("savePreset_pushButton"))
        self.horizontalLayout_6.addWidget(self.savePreset_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 6)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.log_textEdit = QtGui.QTextEdit(self.centralwidget)
        self.log_textEdit.setObjectName(_fromUtf8("log_textEdit"))
        self.verticalLayout.addWidget(self.log_textEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.task_comboBox = QtGui.QComboBox(self.centralwidget)
        self.task_comboBox.setObjectName(_fromUtf8("task_comboBox"))
        self.horizontalLayout_2.addWidget(self.task_comboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.save_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.save_checkBox.setObjectName(_fromUtf8("save_checkBox"))
        self.horizontalLayout.addWidget(self.save_checkBox)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.output_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.output_lineEdit.setText(_fromUtf8(""))
        self.output_lineEdit.setObjectName(_fromUtf8("output_lineEdit"))
        self.horizontalLayout.addWidget(self.output_lineEdit)
        self.ref_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.ref_radioButton.setObjectName(_fromUtf8("ref_radioButton"))
        self.horizontalLayout.addWidget(self.ref_radioButton)
        self.dev_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.dev_radioButton.setObjectName(_fromUtf8("dev_radioButton"))
        self.horizontalLayout.addWidget(self.dev_radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.batch_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.batch_checkBox.setObjectName(_fromUtf8("batch_checkBox"))
        self.verticalLayout.addWidget(self.batch_checkBox)
        self.publish_pushButton = QtGui.QPushButton(self.centralwidget)
        self.publish_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.publish_pushButton.setObjectName(_fromUtf8("publish_pushButton"))
        self.verticalLayout.addWidget(self.publish_pushButton)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.workFile_pushButton = QtGui.QPushButton(self.centralwidget)
        self.workFile_pushButton.setObjectName(_fromUtf8("workFile_pushButton"))
        self.gridLayout_3.addWidget(self.workFile_pushButton, 0, 0, 1, 1)
        self.outputFile_pushButton = QtGui.QPushButton(self.centralwidget)
        self.outputFile_pushButton.setObjectName(_fromUtf8("outputFile_pushButton"))
        self.gridLayout_3.addWidget(self.outputFile_pushButton, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        rigPublishWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(rigPublishWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        rigPublishWin.setMenuBar(self.menubar)

        self.retranslateUi(rigPublishWin)
        QtCore.QMetaObject.connectSlotsByName(rigPublishWin)

    def retranslateUi(self, rigPublishWin):
        rigPublishWin.setWindowTitle(QtGui.QApplication.translate("rigPublishWin", "PT rig publish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("rigPublishWin", "Current Scene : ", None, QtGui.QApplication.UnicodeUTF8))
        self.scene_label.setText(QtGui.QApplication.translate("rigPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("rigPublishWin", "Asset Name : ", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_label.setText(QtGui.QApplication.translate("rigPublishWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("rigPublishWin", "Command list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("rigPublishWin", "Excecute List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("rigPublishWin", "cmd path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("rigPublishWin", "Preset : ", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("rigPublishWin", "Name : ", None, QtGui.QApplication.UnicodeUTF8))
        self.savePreset_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Save Preset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("rigPublishWin", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("rigPublishWin", "Publish Task", None, QtGui.QApplication.UnicodeUTF8))
        self.save_checkBox.setText(QtGui.QApplication.translate("rigPublishWin", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("rigPublishWin", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.ref_radioButton.setText(QtGui.QApplication.translate("rigPublishWin", "Ref", None, QtGui.QApplication.UnicodeUTF8))
        self.dev_radioButton.setText(QtGui.QApplication.translate("rigPublishWin", "Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.batch_checkBox.setText(QtGui.QApplication.translate("rigPublishWin", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Run Command", None, QtGui.QApplication.UnicodeUTF8))
        self.workFile_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Open work file", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFile_pushButton.setText(QtGui.QApplication.translate("rigPublishWin", "Open output file", None, QtGui.QApplication.UnicodeUTF8))

